version: "3.0"

services:
    app:
        build: app
        volumes:
          - ./app:/usr/src/app
          - ./app/node_modules:/usr/src/app/node_modules
        ports:
          - 3000:3000

    mongodb:
        image: mongo
        restart: always
        ports:
          - 27018:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
          - mongodb:/data/db

volumes:
  mongodb: